### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by cabotine** [wort-schule/wort.schule#116]
Looking at the advanced search we would have to check if we can filter for all the fields we have in the database:

- Wortanfang, Wortende
- Wort enthält (egal wo)
- Silben
- Kategorie (Hierarchien sichtbar machen)
- Thema
- Stichwörter

Advanced filters (neccessary for teachers), those can be hidden and pop up if you click on "mehr Filter anzeigen"
- Konsonante-Vokale-Folge
- Verwendete Buchstaben (muss nur Wörter anzeigen die mit den Buchstaben bildbar sind)
- Rechtschreibphänomene
- Strategien
- Quelle (nur sichtbare Quellen)
- Modellwort
- Fremdwort (preferably is a Fremdwort or please no Fremdwort)
- Zusammensetzung (preferably is a Zusammensetzung or please no Zusammensetzung )
- Beispielsatz (preferably has an example sentence or has no example sentence)
- Singular/Pluralwörter (this one was there, but disappeared)
- Zahl der Silben
- Reimwörter suchen (has Reimwörter)
- Wortart (relevant für Funktionswörter)

Wortartspezifisch:
Substantive
- Geschlecht
Adjektive
- Absolutes Adjektiv
- Unregelmäßige Komparation
- Unregelmäßige Deklination
Verben
- Subjektloses Verb
- Starkes Verb
- Perfektbildung über "haben"
- Perfektbildung über "sein"

**Comment by wintermeyer** [comment]
Mental note (siehe https://github.com/wort-schule/wort.schule/issues/171#issuecomment-1438994080):

We figured out which are the filters useful for students:
Wortanfang, Wortende
Wort enthält (egal wo)
Silben
Kategorie (Hierarchien sichtbar machen)
Thema
Stichwörter
Wortart

Advanced filters (neccessary for teachers), those can be hidden and pop up if you click on "mehr Filter anzeigen"
Konsonante-Vokale-Folge
Verwendete Buchstaben (muss nur Wörter anzeigen die mit den Buchstaben bildbar sind)
Rechtschreibphänomene
Strategien
Quelle (sichtbar/unsichtbar)
Modellwort
Fremdwort (preferably is a Fremdwort or please no Fremdwort)
Zusammensetzung (preferably is a Zusammensetzung or please no Zusammensetzung )
Beispielsatz (preferably has an example sentence or has no example sentence)
Singular/Pluralwörter
Zahl der Silben
Reimwörter suchen (has Reimwörter)

Wortartspezifisch:
Substantive
Geschlecht

Adjektive
Absolutes Adjektiv
Unregelmäßige Komparation
Unregelmäßige Deklination

Verben
Subjektloses Verb
Starkes Verb
Perfektbildung über "haben"
Perfektbildung über "sein"

**Comment by wintermeyer** [comment]
@xamiam Wann hast Du Zeit für ein Brainstorming dazu?

**Comment by phylor** [comment]
## Todos

- [ ] Mehr-Button und Weniger-Button für Advanced Filter
- [ ] Stichwörter: bei einer Auswahl danach nur noch Stichwörter anzeigen, die auch in den Resultaten dabei sind. Stichwörter aber nur ausgrauen.
- [ ] Boolean Filter: Fremdwörter ausschliessen, z.B. "Bluetooth", spezifisch nach "ja" oder "nein" oder "egal" suchen
- [ ] Suchfilter schliessen: Filter rauslöschen wenn man auf den einfachen Filter wechselt
- [ ] TomSelect Fehler
- [ ] In "Alle Ergebnisse" umbenennen, Zahlen in Klammern dahinter. Auf Mobile nebeneinander mit Umbruch

**Comment by cabotine** [comment]
Something really useful would be the filter: "Has image".
Thank you!
