### ISSUE TITLE
Index of all words

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#120]
We need to give Google a way to crawl to all words. We should do a `sidemap.xml` in the future too but I think a good old Index of all words gets the job done right now for all sorts of search engines and even might help some humans too.

## Tasks

- [ ] Create a `/seite/wort-index/` area which has sub pages for a-z. On each page list all the words for that letter. Order by alphabet.
- [ ] Include Plural and "Steigerungsformen"
- [ ] Create pagination for each letter. 
- [ ] Create a link in the footer of each page to `/seite/wort-index/`

**Comment by wintermeyer** [comment]
@phylor Serge, can you show Benny the ropes? How can he access the plural and Steigerungsformen? Thanks!

**Comment by phylor** [comment]
> @phylor Serge, can you show Benny the ropes? How can he access the plural and Steigerungsformen? Thanks!

Sure!

@phortx

* `Words#name` is always the base form. For example, singular for nouns or the root of the verb.
* The plural for nouns is in `Words#plural`
* For adjectives, the sequence is `Words#name`, `Words#comparative`, `Words#superlative`
* For verbs, conjugations can be found in `present_singular_1`, `present_singular_2`, `present_singular_3`, `present_plural_1`, `present_plural_2`, `present_plural_3`. The same exist for the past tense (replace `present` with `past`).

You can also compare the views (e.g. `app/views/verbs/show.html.haml`) with the UI if you are unsure.

**Comment by phortx** [comment]
@phylor Thanks, Serge, that helps a lot :)

**Comment by phortx** [comment]
See https://github.com/wort-schule/wort.schule/pull/149
