### ISSUE TITLE
WIP Registration as student or teacher

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#152]
## Goals

* A teacher should be able to sign up and create a school
* A student should be able to sign up without a school

### Sign up

* Before sign up, the user needs to choose whether they want to sign up as a student or as a teacher

* A teacher invites another teacher into a school (either an existing account or an email address without an account)
* A user who signs up as a teacher may create a new school. The school is then in sandbox mode.
* For every new school, a postal address needs to be entered.
* When creating a new school, the system generates a letter with a verification code which is sent to the school.
* A school admin or teacher may enter the verification code in a school to unlock/verify it.
* Schools in sandbox mode may only add 5 teachers.
* If a teacher signs up to an existing school, another teacher or school admin needs to approve it
* A student should be able to ask for permission to join a school
* A teacher or school admin can approve requests to join a school of teachers or students
* A new role school admin is created
* A user may have multiple authorization roles (e.g. `teacher` and `school_admin`)
* A new role `lecturer` allows a user to change words. Students, teachers and school admins may have this role.
* A teacher or school admin can request the system to create x accounts. The system then creates the accounts (including first and last name) and displays usernames and passwords. Passwords are not stored in cleartext in the system, so the system only shows the passwords once. The system adds clearly visible instructions on how to print the current page and may offer a button to do so easily.
* A teacher or school admin may reset the password of any student belonging to one of their schools. The password is then shown in cleartext (only once).

## Requirements for later

* Names of word lists must only contain emojis or words from the database (case insensitive).

## Questions / To be discussed

* Do usernames of fantasy accounts need to be edited by school admins or teachers before creating them?
* How do we generate usernames of fantasy accounts? `Faker::Name.unique.name`?
* As we currently use email address login, may we generate 
* What is the permission difference of school admins and teachers? Do we need a school admin at the moment?
* Names of word lists: What do we do about cases? For example, `Die beste Tierliste`, but we only store `(am) besteN` in the database. People are still able to combine `heil` and `sieg` which would be valid, as we probably have the words in the database. So we still might need some sort of blacklist or some standard profanity filter.
* If you sign up to an existing school, teachers and students both need to wait for an approval to join the school, correct? This slows the sign up down a bit. The only way I could think of that we could securely avoid this, is by using email confirmation and the domain of the school to automatically grant access. So if `hanna@schule-hessen.de` signs up and confirms the email address and we know that `schule-hessen.de` belongs to `Schule Hessen`, Hanna would automatically be granted access without manual approval. I assume that most schools have email addresses for their teachers, so that could speed up teacher sign ups. We would still need the manual approval for cases where they don't have that email setup, so this might also be a future extension?
* Currently, students can be invited to a learning group. Can we keep this behavior or do students additionally need to be invited to a school (without a learning group)?

## Todos

* [ ] Add radio boxes or a select list to the sign up form to choose the initial role, either `student` or `teacher`

![image](https://user-images.githubusercontent.com/1394828/213411157-770eddad-09f8-4a7d-b178-599698a76868.png)

* [ ] After sign up the profile page is currently shown. Enhance the page so that the user may search for a school or create a new school.
* [ ] Add `School#validated:boolean` with `default:false`
* [ ] Add `User#username` to support login with usernames, cf. https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address

**Comment by phylor** [comment]
@wintermeyer This is the issue about the new sign up. Please have a look. I added some questions which came to my mind while writing everything down.

**Comment by wintermeyer** [comment]
> A teacher invites another teacher into a school (with an existing account)

A teacher invites another teacher into a school by adding the email address. If the account already exist it is linked to the school. If it isn't an email is send to that teacher with instructions how to sign in. We use a connection table which stores the email address as one attribute and the school_id as the other attribute. So that when the new teacher creates his/her account he/she automatically gets assigned into the school.

**Comment by wintermeyer** [comment]
The letter idea has one flaw: We don't know if that is the address of a school. It could be the address of a student. **Let's not send the letter** and kill the code idea for now. Put every new school into sandbox mode and send an email to a super-admin so that they can approve it manually. It is not ideal, but the safest way we can do right now.

**Comment by wintermeyer** [comment]
> The system then creates the accounts (including first and last name) and displays usernames and passwords.

In that case the system creates accounts just with fantasy usernames and random passwords. No first and last name.

**Comment by phylor** [comment]
Obsoleted by #154.
