### ISSUE TITLE
Accounts 2.0 | Remove schools, rework signup and accounts

### ISSUE THREAD

**Issue by phylor** [wort-schule/wort.schule#154]
Previous issue and discussion: https://github.com/wort-schule/wort.schule/issues/152

## Requirements

* New roles:
  * `lecturer`: creates and edits words
  * `admin`: as is, all permissions
  * `user`: normal account, create learning groups, create word lists
* New roles on `LearningGroup`:
  * `member`: receives words from word lists of learning group
  * `group_admin`: may add/remove members, may generate accounts
* A generated account is automatically associated to the learning group the account was created from
* A group admin may reset passwords of generated accounts of their learning group, the password is shown once
* Generated accounts have dummy email addresses ending in `@user.wort.schule`. They don't work but make it possible to use a generated account in multiple learning groups.
* Real E-Mails now need to be confirmed, otherwise the app cannot be used

## Questions

Q: Currently, if a word list is added to a learning group, all words of that list are added to the Wörterklinik of all students of that group. Do group admins also receive those words into their Wörterklinik?
A: Yes.

## Todos

* [x] Remove and destroy all schools in the database
* [x] Convert all user roles `Student` and `Teacher` to `User`, remove permissions
* [x] Add a new role `lecturer` (use old `Teacher` permissions as a starting point)
* [x] Add `LearningGroupMembership#role` as `%i[group_admin member]`
* [x] When creating a learning group, the creator gets the `group_admin` automatically
* [x] Add button to make someone a group admin in a learning group (only confirmed accounts are allowed to be group admins)
* [x] Add button to remove someones group admin rights
* [x] Add devise email confirmations
* [x] Force all users (except `@user.wort.schule`) to confirm their email address before using the app
* [x] Add button to reset a password of a generated user
* [x] Allow to generate accounts from within a learning group. Let the user choose how many are generated. The system then generates `email_adress` ending in `@user.wort.schule` and a `password`. Username and passwords are then shown to the user. Add instructions on how to print that page and note that these passwords are later not visible anymore.
* [x] Hide `@user.wort.schule` from profile and wherever we display the email address
* [x] Change invitation to learning group to show a user input instead of all users. Either an email address or an email address without `@user.wort.schule` may be entered.

## Misc

We don't display the `@user.wort.schule` part in the web interface. Those accounts are always referred as the `xyzsefasdf` account and not as the `xyzsefasdf@user.wort.schule` account. When ever somebody enters `xyzsefasdf` we add the `@user.wort.schule` internally.

**Comment by phylor** [comment]
@wintermeyer A security concern we should be aware of, about invitations to learning groups.

If you have a field with an email address and the entered account is immediately added to your learning group, you could iterate through email addresses to figure out who is signed up. This is a similar issue one has when resetting a password via email address. As you usually don't want to leak whether someone uses a service, nowadays the system would usually show "we have sent you an email with a reset link" even if that email does not exist in the sytem.

If we want to do it the proper way, we would do:

1. Enter an email address of an account you want to invite to your learning group
2. The system says that an invitation has been sent and the invitee needs to accept it
3. The invitee receives the invitation email and accepts the invitation
4. Only then is the invitee added to the learning group

Of course, for generated accounts, no email would be sent and they would be added immediately.

Do you share that concern? How shall we proceed? I'm not against just accepting the concern and living with it.

**Comment by wintermeyer** [comment]
> If you have a field with an email address and the entered account is immediately added to your learning group, you could iterate through email addresses to figure out who is signed up.

An other issue would be that I could invite somebody to a learning group who doesn't want to be in that group.

Long story short: The one person has to see a "Wenn es diese E-Mail Adresse im System gibt, dann wird eine Einladung per E-Mail rausgeschickt. Der Account erscheint in der Lerngruppe, sobald der Adressat die Einladung bestätigt hat." and the other person has to receive an email with a confirmation link.

**Comment by wintermeyer** [comment]
@phylor Sorry, I didn't read your message to the end before answering the first part.
