### ISSUE TITLE
Wörterklinik

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#16]
This is just a dummy issue to keep track of the work. Can be used for questions and discussions.

## Todos

Wörterlisten:

* [x] Wortlisten anzeigen
* [x] Wortliste anzeigen, Wörter löschen
* [x] Wortliste erstellen und bearbeiten
* [x] Listen: öffentlich und privat
* [x] Wörterlisten haben kein Theme
* [x] Wörter show: Wortliste anzeigen, auf denen dieses Wort vorkommt. Low Prio, da bei den Wörterkarten-Themes diese Info ohnehin nicht angezeigt wird
* [x] Filter: alle Wörter zur Liste hinzufügen
* [x] Schüler dürfen nur private Listen erstellen, keine öffentlichen
* [x] Einzelnes Wort zu Wortliste hinzufügen
* [x] Write spec: Remove word from list

Lerngruppen:

* [x] Lerngruppe: Default Theme für jeden Worttyp
* [x] Lerngruppe: mehrere Wortlisten zuweisen
* [x] Werden Listen einer Lerngruppe geändert, werden die Wörter aus der Lernkartei der Schüler gelöscht oder hinzugefügt
* [x] Es werden aber nur Wörter entfernt, die nicht auch noch in anderen Wörterlisten derselben Lerngruppe vorkommen (TBD)
* [x] Words should only be once on the flash card lists even if in multiple word lists
* [x] Adding a word to a connected list adds it to all student's flashcards
* [x] Removing a word from a connected list, removes it from all students

Wörterklinik:

* [x] Fixe Listen Fach 1-5 erstellen pro User
  * [x] Wörter in Lernkartei mit Liste speichern
* [x] Liste mit allen Wörtern aus Lernkartei. Listen, die jeweils nur 1 Fach zeigen
* [x] Wird ein Schüler einer Lerngruppe hinzugefügt, werden die Wörter ins 1. Fach kopiert
* [x] Add flash card lists to existing students

## Next todos

* [x] Mit Klick auf Wort darunter Buttons anzeigen:
  * [x] ins nächste Fach verschieben
  * [x] in Fach 1 verschieben
  * [x] Wort anzeigen
  * [x] aria setzen für Screenreader
* [x] Wörter in Fächern alphabetisch sortieren
* [x] DnD entfernen
* [x] Konfetti Animation bei Verschieben der Wörter ins nächste Fach, konfigurierbar machen und dokumentieren

## Nice to have

* [ ] Wörterlisten favorisieren
* [ ] Als Lehrer Wortliste bei Schülern als Favorit setzen
* [ ] Wörter show: Fächer anzeigen, wo dieses Wort vorkommt. Low Prio, da bei den Wörterkarten-Themes diese Info ohnehin nicht angezeigt wird
* [ ] Konfigurierbare Slugs mit Kurz URL für Wortlisten
* [ ] ~~Papertrail für Wörter in Fächern, damit man weiss wann welches Wort von welchem Fach in welches verschoben wurde~~

**Comment by phylor** [comment]
@wintermeyer An edge case:

Assume that we have the same word on multiple word lists. These word lists are added to a learning group.

That one word will be added to all students. However, I assume it will only be added once, even if it appears on multiple lists.

Now, what happens if one of these word lists is removed from the learning group? The word should then **not** be removed from the students (because it is still on other word lists, which are still connected to the learning group), correct?

**Comment by cabotine** [comment]
I love the Wortlisten-feature. Just in the overview the nouns should also include the "articles".

![grafik](https://user-images.githubusercontent.com/8180537/204145372-36d60df2-e017-4125-b99d-ddfd834450a5.png)
