### ISSUE TITLE
Wortkarten

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#17]
a.k.a Themes

Dummy Issue, um den Überblick zu behalten. Kann für Fragen und Diskussionen benutzt werden.

## Todos

* [x] Grund-Template und Layout in Liquid erstellen (für 3 Wortarten) inkl. Definition und Dokumentation der verfügbaren Variablen
* [x] ~~Wort als Wortkarte anzeigen (Button/Link auf Wortseite)~~
* [x] Als Lehrer Template kopieren und anpassen

Aufräumen:

* [x] Card in Theme umbenennen
* [x] Wörterkarten: Favorit entfernen
* [x] Fix preview of word cards
* [x] Remove theme selection from words
* [x] Add support for function words (if it's not too much work)

Themes:

* [x] Wenn Theme sich ändert bei Lerngruppe, allen Schülern dieses Theme setzen
* [x] Code Editor für Templates der Themes
* [x] Wortkarten: Print CSS
* [x] Fix page titles when rendering themes
* [x] Profil: Wörterkarten Default für jeden Worttyp setzen.
  * [x] Standardansicht immer als erste Theme verwenden. ~~Service Klasse schreiben, die Themes von User zurückgibt.~~
  * [x] Migration für `User#theme_noun`, `User#theme_verb`, `User#theme_adjective`
  * [x] UI im Profil
  * [x] Spec: Wort anzeigen, im Profil Theme updaten, Wort nochmals anzeigen

**Comment by wintermeyer** [comment]
> @wintermeyer I only planned to add themes/cards for nouns, verbs and adjectives. Do we also need them for function words?

Good question. If it is a lot work: No. Otherwise: Yes.

**Comment by cabotine** [comment]
> > @wintermeyer I only planned to add themes/cards for nouns, verbs and adjectives. Do we also need them for function words?
> 
> Good question. If it is a lot work: No. Otherwise: Yes.

In general yes. In tendency they should be less complicated, because they contain less special information. Only special thing: the icon for the word type changes. One icon for pronouns, one for articles, one for ....

**Comment by phylor** [comment]
> [..] Only special thing: the icon for the word type changes. One icon for pronouns, one for articles, one for ....

We haven't discussed icons yet. Is that a small image visualizing the word type? Is it high priority that it is included?

**Comment by cabotine** [comment]
> > [..] Only special thing: the icon for the word type changes. One icon for pronouns, one for articles, one for ....
> 
> We haven't discussed icons yet. Is that a small image visualizing the word type? Is it high priority that it is included?

Yes, it is a small image for visualizing the word type. And yes they are important ;)
I can get us the images next week. PNG? Do you have the Word-File that is describing the wordcards? Sorry if I am messing things up, I don't know what you spoke about. Maybe I talk to Stefan.

**Comment by phylor** [comment]
> Yes, it is a small image for visualizing the word type. And yes they are important ;) I can get us the images next week. PNG? Do you have the Word-File that is describing the wordcards? Sorry if I am messing things up, I don't know what you spoke about. Maybe I talk to Stefan.

Yes, maybe it's better if you quickly talk to Stefan!

As far as I understood, we'll allow teachers to create their own templates for the word cards. The system provides a default template to start out from. I'm not sure if we provide more out-of-the-box and how sophisticated these will be.

Images will be technically difficult to dynamically include in the templates, as long as they are not predefined. If so, SVGs would be preferred for printing, but PNGs will also work.

**Comment by wintermeyer** [comment]
> Yes, maybe it's better if you quickly talk to Stefan!

I talked with @cabotine today. We are going to tackle this after we implemented the current stuff.

Sneek peak: We are talking about "magic" tags which do stuff like display a green circle in case it is a verb or a red in case it is a xyz. But we are not there yet.
