### ISSUE TITLE
Add Kölner Phonetik as an phonetic algorithm for easier search

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#20]
The typical user of this system will search for words without the proper spelling. To help them find the word they are searching we should implement https://de.wikipedia.org/wiki/Kölner_Phonetik as a secondary search tree. 

With that additional search index in place we can find "Fahrrad" even by searching for 

- Farad
- Farat
- Fahrraad
- Vahrad

## Tasks

- [x] Add a method `to_cologne_phonetics(input)` which converts a given input string into Kölner Phonetik according to the rule set of https://de.wikipedia.org/wiki/Kölner_Phonetik
- [x] Add a migration for a new attribute `cologne_phonetics` in `words`. Don't forget the index.
- [x] Add a hook so that the `cologne_phonetics` attribute gets updated every time the value of a `word` gets updated.
- [x] Add a migration which fills all the `cologne_phonetics` fields of the existing data.
- [x] Change the index page search so that it uses https://de.wikipedia.org/wiki/Kölner_Phonetik.

The last step is tricky. We have to find a way to display which words where 100% matches to the search query and which where Kölner Phonetik matches.

**Comment by cabotine** [comment]
You are my hero!

**Comment by philipp-kempgen** [comment]
Did you investigate Trigram search?
https://en.wikipedia.org/wiki/Trigram_search
https://www.postgresql.org/docs/current/pgtrgm.html
Maybe use your proposed implementation of Cologne phonetics for the matches, then use trigram search (or soundex?) to order those matches, based on distance/similarity?

**Comment by phylor** [comment]
@wintermeyer The basics of this are implemented.

Questions and thoughts about the search results:

1. Currently we were searching for exact matches contained in the word. That is: `LIKE %my_term%`. There is no ordering yet. So when searching for `ball`, you might see `Basketball` before `Ball`.
2. Now we search phonetically, looking for an exact match. For example, `Fahrrad` is represented as `372`. We only look for words which have the exact same phonetics `372`. **Shall we also do an "include" search here? So we would find any words which have `372` somewhere in their phonetics? This would also find `2372`.**
3. We could show an indication as the following in the search results, but I don't see the benefit for the user. We just try to find the best matches for the search term. There will always be mismatches in there. For example `Fahrrad` and `Wort` both have `372` as phonetics.

![image](https://user-images.githubusercontent.com/1394828/205328859-6c998d4b-9435-41ad-9128-2fc7f0dbcfd3.png)

4. I don't have any experience with Trigram search based on phonetics. Shouldn't the phonetics already generalize enough, so that Trigram is no longer necessary?
5. I believe what we definitely should focus on is the order of the displayed results. That is, we need to rank each result on how good it matches to the search term. Exact character matches should then be ranked higher than phonetic matches.

**Comment by wintermeyer** [comment]
> @wintermeyer The basics of this are implemented.

Great!

> 5. I believe what we definitely should focus on is the order of the displayed results.

I agree with you. I think we have to accept that we will not find the best solution in the first version. This will iterate a bit over the next couple of months.

My thoughts for now:
- Let's ask @xamiam for a way to display that these "Treffer" are phonetic once so that the user (especially the kids) realise that this is not a 100% Treffer. We need a solution for the pull-down list in the index search page and on the result page.
-  Regarding matching of phonetic I'd like to suggest `LIKE my_term%` and not `LIKE %my_term%`. Otherwise we'll end up with too many possible matches and I think that most students (kids) will start with the beginning of a word.
- When we have perfect matches in the normal search than we shouldn't invest much effort in searching for additional phonetic ones.

This is the "workflow" of dealing with search input I think is the best for now:
- 1st letter: Let's assume that the user wants to do a `LIKE my_term%` search in the normal index.
- 2nd letter: Switch to a `LIKE %my_term%` search in the normal index and add the order of `hit_counter` (https://github.com/wort-schule/wort.schule/issues/91) as a sorting mechanism.
- 3nd letter: No change unless we have zero results. In that case use phonetic search.
- 4th letter: Always add phonetic search to the mix. In case there are results of `LIKE my_term%` display them first. Then add `LIKE %my_term%` and then add phonetic. Sort the sum of all by `hit_counter`. That should be a good enough first attempt at this problem.

# Important

We are heading for a "better than before" and not for a "perfect" solution. 80% is helping a lot of people. Done is so much faster to implement than perfect. We can and will fine tune it in the future.

**Comment by cabotine** [comment]
I think adding the trigram search could really help lower the number of issues a lot. (Sorry to come up with it again.) 
Cannot stop thinking about it.
See here https://github.com/wort-schule/wort.schule/issues/118
