### ISSUE TITLE
Better URL for https://wort.schule/search

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#24]
The problems with https://wort.schule/search:

- /search is an English word. It should be `suche`
- /suche will become a problem with [friendly_id](https://github.com/norman/friendly_id)

# Task

- [x] Move https://wort.schule/search to https://wort.schule/seite/suche
- [x] ~~Add `seite` to forbidden slugs for friendly ID~~
- [x] ~~Add migration to change existing slug `seite` to something else (if that exists)~~

**Comment by wintermeyer** [comment]
> It might be a good idea to move everything (except the friendly_id) into a namespace, as originally proposed. 

👍

> Ideally, that namespace doesn't exist in German.

I disagree with that. I propose we use `/seite`. That is a word most can somehow understand. `/intern` doesn't make sense for all pages. `/app` is not German and we are dealing with a German audience. But in the worst case I can live with `/app` but I prefer `/seite`.

> We have to take care with the German URLs that the code doesn't get too complex and that we don't let German vocabulary drip into the code base. That is, the Rails controller should ideally be called `SearchesController` and not `SucheController`.

👍

I am only talking about the route paths. Not about the actual code.

**Comment by wintermeyer** [comment]
Could become obsolete because of https://github.com/wort-schule/wort.schule/issues/67

**Comment by cabotine** [comment]
I think we still need the power search site, which enables you to search for everything you ever dreamed of as a German teacher.

**Comment by wintermeyer** [comment]
> I think we still need the power search site

You can't have your cake and eat it too. Our current goal is an easy to use GUI. Most of our users are not power users. We have to find a way to make them happy.  The current power search scares most users. 

With a bit of luck and UX magic we find a solution without having to provide an extra search page. Let’s try that first. If we can’t find a good solution we’ll add an extra power search page.

**Comment by phylor** [comment]
For now, I moved everything below a scope `/seite`. For example, we now have `/seite/search`, `/seite/nouns`, `/seite/schools`, etc. The idea is that everything application related is "below" `/seite/...`. Only the word URLs such as `/adler` remain at the top level.

This issue is about renaming `/search` to `/suche` though. Do we still want to rename that?

If we do rename it, shouldn't we then also rename all other routes? For example, `/seite/substantive` instead of `/seite/nouns`.

I'm looking for consistency: I'd vote either to change all of the routes into German or none of them. Translating them into German will be a small pain technically and we can't translate all of them (Devise, ActiveStorage, etc.).

But maybe that whole discussion is obsolete because of #67.

@wintermeyer What do you think?

**Comment by wintermeyer** [comment]
> This issue is about renaming `/search` to `/suche` though. Do we still want to rename that?

Yes.

> If we do rename it, shouldn't we then also rename all other routes? For example, `/seite/substantive` instead of `/seite/nouns`.

Those pages are goner anyway. With the new idea of how we search those pages will not be needed any more.

> But maybe that whole discussion is obsolete because of #67.

It is kind of obsolete.

I close this issue for now. We'll wait for the outcome of #67
