### ISSUE TITLE
Generate and attach TTS generated Audio Files

### ISSUE THREAD

**Issue by wintermeyer** [wort-schule/wort.schule#68]
# Idea

Provide an audio player on the #show view of each word to play an attached MP3 recording of the word. A pure HTML solution is preferred. No need for a complex JavaScript player with a million functions.

# Tasks

- [ ] Create a class which handles the TTS stuff by using Google's WaveNet technology (https://cloud.google.com/text-to-speech/#section-11) to generate an audio file (MP3?) and attach that file to the word model. Provide a possibility in the configuration of the Rails project to customise configuration "stuff" (e.g. speed, API keys and kind of voice). 
- [ ] We use multiple voices which do a round robbing. The configuration has to accept an array with the to used voices. 
- [ ] Store the audio files in the production server file system. There should be a max file size of each audio file.
- [ ] Google WaveNet has a rate limit for free projects. And we need to have a configuration for the pause between each call. Keep that in mind and make it part of our configuration. Info: We will not be able to run all words in the first month.
- [ ] Create some sort of queuing system. Either by using [Active Job](https://guides.rubyonrails.org/active_job_basics.html) or by reinventing the wheel. Obviously the system should be able to survive a reboot of the server and a deployment with a restart of a new software version.
- [ ] Add an `enable_tts` boolean attribute to the word model (including the #edit form). It should be `true` by default. When ever it is changed, either a new audio file has to be generated or the old file has to be destroyed (from `true` or `nil` to `false`). Please add after_update/create hooks accordingly. 
- [ ] Add the audio player to the #show view and activate it if the audio file is attached to the word.
- [ ] Write tests. Use common sense.
- [ ] Create a task which loops through all words which don't have an audio file attached and triggers the TTS call.
- [ ] Add some minimal documentation to the README.md how to use the class/method/task.
- [ ] Make sure that the system is not triggered/used when the API keys are missing. Most developers will not have an API key ready when they first start wort.schule locally. They should not run into any trouble.

Please use vanilla build in Rails features when ever possible. Please use this issue to discuss and ask questions.

**Comment by cabotine** [comment]
It would be great if we have an easy way to generate examples with the various options, so we can find out (through testing with students) which options are important.

The platform should use both male/female voices (varying from word to word).
And the amount of characters produced/used per months should be limited according to the Google Cloud limits.

**Comment by wintermeyer** [comment]
> It would be great if we have an easy way to generate examples with the various options, so we can find out (through testing with students) which options are important.

That is out of scope for the current budget. We will have to find the right settings manually. 

> The platform should use both male/female voices (varying from word to word). And the amount of characters produced/used per months should be limited according to the Google Cloud limits.

I’ll add it to the tasks.

**Comment by wintermeyer** [comment]
@phortx Please feel free to suggest a better solution for the queuing and rate limit. Maybe a queue is not the best solution here. Maybe an additional ’waiting_for_tts‘ Boolean attribute and a cron job is a better and much easier to implement solution.

**Comment by cabotine** [comment]
> > It would be great if we have an easy way to generate examples with the various options, so we can find out (through testing with students) which options are important.
> 
> That is out of scope for the current budget. We will have to find the right settings manually.
> 

I didn't mean automagically, but to generate them by changing the values manually (maybe via an options page ;) ).

**Comment by philipp-kempgen** [comment]
Random thoughts (they are really just that: thoughts):

- There needs to be some kind of background job, that various places in the code can trigger. A cronjob should probably be able to trigger it, as well as the GUI.

- Adding an API key should trigger that background job, so files are generated when you add an API key later on.

- New developers may not have the cronjob entry. So maybe some action/activity on the web page should be able to trigger the job.

- Maybe store a timestamp of when the audio file was generated. Maybe you want to re-generate the audio files at a later time, one by one, oldest first.

- Also store a timestamp ("being_generated_since" or something, can be nil) that says when the word was put into the queue for the audio file to be generated, so the background job doesn't accidentally try to generate the same thing twice if invoked more than once. nil means that the file _isn't_ currently being generated (either becaus the file exists already or because it was never generated).
	- Have some cronjob periodically clean entries with being_generated_since older than say 30 minutes, just to avoid zombies.

- Maybe words added via the GUI just now should get a higher priority in the queue (or queue-like mechanism) than background stuff such as (re-)generating words, that have been in the system for longer.

- You may want some property in the database table to invalidate audio files without deleting them straight away. I.e. a wod is changed (if that ever happens), then delete the audio file straight away, but if you change say the voice or something, then mark the audio file as outdated but still keep it until a new file is generated.

- Maybe there shouldn't be a queue, but some task that is triggered periodically and/or via the GUI. That task is supposed to figure out what audio file to generate next. It could do that by a couple of rules like so:
	
	- Query the database for the newest word with being_generated_since == nil and without an audio file.
		-If there is one => mark it as currently being generated in the database (being_generated_since), generate the audio file, when done set being_generated_since = nil. End of the task, start next iteration from the top!
	
	- If the query above didn't find a word, then continue here:
	
	- Query the database for the newest word with being_generated_since == nil.
		- ...

- Have appropriate (combined!) indices on the database table for those queries, so the query can be answered from the index alone.

- Also store some timestamp(?) if some audio file failed to generate, so the background job doesn't keep working on the same thing forever.

**Comment by philipp-kempgen** [comment]
What that generator task does as described above would need some refinement, e.g. to have files marked as outdated somewhere in between or as the last priority.

**Comment by wintermeyer** [comment]
About cronjob vs. trigger vs. queue: It would be nice to have a possibility to trigger the API call to generate a new file. BUT that is a nice to have feature. It is not necessary. I think a simple cronjob and some more table attributes would serve us well and much quicker (cheaper) to implement. As a bonus it would be a much simpler system. Less that can go wrong.

# Thoughts

- We have to think about the crash scenario. Assuming we have a 'this_is_currently_being_processed' attribute then that attribute has to be set to `false` for all table entries when ever the Rails system gets (re-)started.
- We have no need to hurry. We are limited by the number of possible API calls per month anyway. We can simply set the `waiting_to_be_generated` attribute to `true` and wait for the cronjob to search for the next "thing" to do.
- Please be aware that the initial "fill" will take a couple of months anyway because of the rate limit in the free version. That is no problem.

**Comment by wintermeyer** [comment]
@phortx I updated the initial issue text. Please tell me if anything is missing or not clear.

**Comment by phylor** [comment]
Regarding jobs you could use:

- [Sidekiq](https://sidekiq.org). Quite popular, has a cron plugin to regularly schedule jobs, but requires a Redis instance.
- [good_job](https://github.com/bensheldon/good_job). Stores everything in Postgres, so doesn't require another database. As Sidekiq, also requires a job running process though. It's in very active development and also has a UI to inspect queues and see some statistics.

Most queuing systems drop jobs when failed and don't store them when the Rails process restarts. So you might want to design around that in any case.

**Comment by wintermeyer** [comment]
> * [good_job](https://github.com/bensheldon/good_job). Stores everything in Postgres, so doesn't require another database. As Sidekiq, also requires a job running process though. It's in very active development and also has a UI to inspect queues and see some statistics.

Since maximum performance is not our problem here I'd like to use the PostgreSQL database to eliminate installing one more peace of software.

**Comment by wintermeyer** [comment]
@phortx JFYI: You can auto close an issue by adding `closes #121` to the git comment. Than that issue gets closed automatically once the code has landed in the `main` branch.

https://stackoverflow.com/questions/12235620/automatically-closing-issue-from-pull-request-in-github
